#This defines and manages multi-container applications

# version: "3.9" #version of the docker compose 

services:
  app:
    build:
      context: . #this means we want to build a docker file inside our current directory(where we are currently running docker compose from)
      args:
        - DEV=true #we are using this for development
    ports:
      - "8000:8000" #this maps port 8000 inside our local machine to port 8000 inside our docker container. This is how we can access the network when we want to connect to our server
    volumes:
      - ./app:/app  #mapping  directories from our system into the docker container(we are mapping the app directory that we created to "\app inside our container"). This is because we want the updates that we make to our code in our local project to be reflected in the running container in real time
    command: >  #command used to run the service. 
      sh -c "python manage.py runserver 0.0.0.0:8000"