---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2 #This action checks out your repository so your workflow can access it
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test" #This is the command that runs unit test on our project
      - name: Lint
        run: docker compose run --rm app sh -c "flake8" #This is the command that runs linting on our project
